### ISSUE TITLE
Provide a more correct typescript version

### ISSUE THREAD

**Issue by Gankarloo** [vmware/vrealize-developer-tools#132]
### Description

From time to time I find myself writing sound typescript code only to be stumped when building the project.

As I understand it the vrotsc is based on a much older typescript version than the one included in VS Code.
In VS Code I have now version 5.1.3

and when looking at the vrotsc code it seems to be based of version 3.8.3

Would it be possible to present this infomation or perhaps download the correct version in order for the Intellisense to match the transpile step?

### Example

Today I tried to use Template literal types.

With the default typescript in vscode
![image](https://github.com/vmware/vrealize-developer-tools/assets/12395912/176d9c74-a0cb-45bb-9382-482db88e4a5f)

All seems well until I build the project and it fails with.
![image](https://github.com/vmware/vrealize-developer-tools/assets/12395912/332810fb-ddad-435b-84d4-22a1019de5f8)

But if I manually install and use typescript version 3.8.3 
The Intellisense shows it is not valid.
![image](https://github.com/vmware/vrealize-developer-tools/assets/12395912/f4254da5-e611-409d-adcf-0485ccf3fc90)

**Comment by VenelinBakalov** [comment]
Hi @Gankarloo , thanks for your suggestion! I checked the issue, seems to still be valid, I am moving this to the Build Tools for Aria opensource because I think the improvement should be executed there as part of the core logic because the VS Code plugin only consumes it and builds on top.
I already created a new issue there, containing all the info you provided in the original ticket: https://github.com/vmware/build-tools-for-vmware-aria/issues/215
