### ISSUE TITLE
vRO 7.6  "vRealize Run Action" does not works

### ISSUE THREAD

**Issue by nvodenicharski** [vmware/vrealize-developer-tools#48]
Performing "vRealize Run Action" in vRO 7.6 throws the following error:

Error:
# Running constants.js
# Execution ID: 077cc5c5-877b-41ee-a645-390047b1c044

# An error occurred: 405 - "<!doctype html><html lang=\"en\"><head><title>HTTP Status 405 – Method Not Allowed</title><style type=\"text/css\">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> Request method &#39;POST&#39; not supported</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.37</h3></body></html>"

**Comment by nblagoev** [comment]
This is caused by a change in the vRA 7.6 API. We'll have to support both tho, since 7.3 to 7.5 require POST instead of GET method.

pre-7.6: 
![image006](https://user-images.githubusercontent.com/215676/69734038-fc7a4880-1136-11ea-8c01-644fae0c7a98.png)

post-7.6:
![image007](https://user-images.githubusercontent.com/215676/69734049-0308c000-1137-11ea-8996-70fce9c80670.png)
